### ISSUE TITLE
Very good code

### ISSUE THREAD

**Issue by levisaturnino** [exchangegroup/paged-scroll-view-with-images#1]
Just I like to know how do I let the images through automatic. An auto scroll in 3 sec or 2 sec?

**Comment by evgenyneu** [comment]
Thanks, you can create an NSTimer that will fire very 3 seconds, calculate the offset of the next page and then do `setContentOffset` with animation. See this Stackoverflow answer for more details: http://stackoverflow.com/a/17169120

**Comment by leandrodavimg** [comment]
Hello I'm using his great code, how can I add tap in scrollview    

The code below works if it is equal to two ()

@IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var pageControl: UIPageControl!
    @IBOutlet var images: YiiPagedImages!

let doubleTapRecognizer = UITapGestureRecognizer(target: self, action: "someAction:")
        doubleTapRecognizer.numberOfTapsRequired = 2
        doubleTapRecognizer.numberOfTouchesRequired = 1
        scrollView.userInteractionEnabled = true
        scrollView.addGestureRecognizer(doubleTapRecognizer)
